#!/usr/bin/env sh

# Global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
# Set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier               ctrl
# Set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2                resize
# Set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1                move

# Spacing 
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12

# Diasble resize for those apps 
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Flux$" manage=off
# yabai -m rule --add app="^Finder$" manage=off
# yabai -m rule --add app="^Spotify$" manage=off

# Space labeling
yabai -m space 1 --label I
yabai -m space 2 --label II
yabai -m space 3 --label III
yabai -m space 4 --label IV
yabai -m space 5 --label V
yabai -m space 6 --label VI
yabai -m space 7 --label VII
yabai -m space 8 --label VIII
yabai -m space 9 --label IX
yabai -m space 10 --label X

# Limelight - kill it and start it each time Yabai starts
# killall limelight &>/dev/null
# limelight &>/dev/null &

# scriptsPath='/Users/kornel/.config/custom-scripts'
# yabai -m signal --add event=window_destroyed action="bash /Users/kornel/.config/custom-scripts/window-focus-on-destroy.sh"

# When Menu Bar hidden and using SpaceBar or SimpleBar
yabai -m config external_bar all:27:0

echo "yabai configuration loaded.."
