-- require('indent_blankline').setup {
--   -- for example, context is off by default, use this to turn it on
--   show_current_context = true,
--   show_current_context_start = true,
--   filetype_exculde = { 'NvimTree', 'packer' },
--   context_patterns = {
--     'class', 'return', 'function', 'method', '^if', '^while', '^for', '^object',
--     '^table', 'block', 'arguments', 'if_statement', 'else_clause', 'jsx_element',
--     'jsx_self_closing_element', 'try_statement', 'catch_clause', 'import_statement',
--     'operation_type'
--   },
-- }
