-- require('lsp-format').setup {}
-- lspconfig.html.setup { capabilities = capabilities }
-- lspconfig.cssls.setup { capabilities = capabilities }
-- lspconfig.astro.setup{}
-- lspconfig.tsserver.setup{}
-- 
-- local languages_to_format = {
  -- 'html',
  -- 'cssls',
  -- 'astro',
  -- 'tsserver',
  -- 'ls_emmet',
  -- 'cssmodules_ls',
  -- 'eslint',
  -- 'jsonls',
  -- 'sumneko_lua'
-- }
-- 
-- for _, lang in ipairs(languages_to_format) do
  -- require 'lspconfig'[lang].setup { on_attach = require('lsp-format').on_attach }
-- end
-- 
-- vim.cmd [[cabbrev wq execute 'Format sync' <bar> wq]]
-- vim.cmd [[cabbrev w execute 'Format sync' <bar> w]]
-- vim.cmd('autocmd BufWritePost * Format')
